=== smlc/iaws-webServices/Application-ServicesVelib/ApplicationVelib-WS/src/main/resources/webservice.serviceuserstory3/RequestContract.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://iaws/ws/contractfirst/station" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="RequestWs3" type="stat:RequestWs3Type" xmlns:stat="http://iaws/ws/contractfirst/station"/>
  <xs:complexType name="adresseType">
    <xs:sequence>
      <xs:element name="numeroRue">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="31"/>
            <xs:enumeration value="38"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:string" name="nomRue"/>
      <xs:element type="xs:string" name="codePostal"/>
      <xs:element type="xs:string" name="ville"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="att" use="optional"/>
  </xs:complexType>
  <xs:complexType name="RequestWs3Type">
    <xs:sequence>
      <xs:element type="stat:adresseType" name="adresse" maxOccurs="unbounded" minOccurs="0" xmlns:stat="http://iaws/ws/contractfirst/station"/>
    </xs:sequence>
    <xs:attribute type="xs:boolean" name="requeteTempsAPied"/>
  </xs:complexType>
</xs:schema>

=== smlc/iaws-webServices/Application-ServicesVelib/ApplicationVelib-WS/src/main/resources/webservice.serviceuserstory3/Request.xml
<RequestWs3 requeteTempsAPied="false" xmlns="http://iaws/ws/contractfirst/station"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://iaws/ws/contractfirst/station RequestContract.xsd" >
    <adresse att="depart">
        <numeroRue>31</numeroRue>
        <nomRue>rue Valade</nomRue>
        <codePostal>31000</codePostal>
        <ville>Toulouse</ville>
    </adresse>
    <adresse att="arrivee">
        <numeroRue>38</numeroRue>
        <nomRue>rue Valade</nomRue>
        <codePostal>31000</codePostal>
        <ville>Toulouse</ville>
    </adresse>
</RequestWs3>
